const MOMENT_DISPLAY_FORMATS = Object.freeze({
  AM_PM: 'A',
  TIME_12HR: 'h:mm A',
  TIME_MILITARY: 'HH:mm',
  MONTH_SHORT: 'MMM',
  DATE: 'D',
  YEAR_MONTH_DATE: 'YYYY/MM/DD',
  MONTH_DATE_YEAR: 'MM/DD/YYYY',
  MONTH_DATE_YEAR_TIME: 'MMM Do, YYYY h:mm A',
  YEAR_MONTH_DATE_SERVER: 'YYYY-MM-DD',
  FULL_DATE_WITH_TIME: 'h:mm A, MMM Do, YYYY',
  FULL_DATE_WITH_DAY: 'ddd MMM Do, YYYY',
  FULL_DATE: 'MMM Do, YYYY',
  DATE_NO_YEAR: 'MMM Do',
  DATE_TIME_NO_YEAR: 'h:mm A, MMM Do',
})

export default MOMENT_DISPLAY_FORMATS
